// Generated by backend/cmd/contractgen. Do not edit.
import Foundation

enum PresentationTextKey: String, CaseIterable, Sendable {
    case appBackendDateMalformed = "app.backendDateMalformed"
    case appBackendMalformed = "app.backendMalformed"
    case appBackendMissing = "app.backendMissing"
    case appBackendNotRunning = "app.backendNotRunning"
    case appBackendRequestCreateFailed = "app.backendRequestCreateFailed"
    case appBackendRequestFailed = "app.backendRequestFailed"
    case appBackendTerminated = "app.backendTerminated"
    case appName = "app.name"
    case appProtocolMismatch = "app.protocolMismatch"
    case commonCancel = "common.cancel"
    case commonClose = "common.close"
    case commonConfirm = "common.confirm"
    case commonCopy = "common.copy"
    case commonOk = "common.ok"
    case commonOpen = "common.open"
    case dialogRestartMessage = "dialog.restartMessage"
    case dialogRestartTitle = "dialog.restartTitle"
    case logsClear = "logs.clear"
    case logsClearFailed = "logs.clearFailed"
    case logsClearMessage = "logs.clearMessage"
    case logsClearTitle = "logs.clearTitle"
    case logsEmpty = "logs.empty"
    case logsOpenFile = "logs.openFile"
    case logsRefresh = "logs.refresh"
    case logsSubtitle = "logs.subtitle"
    case logsTitle = "logs.title"
    case menuQuit = "menu.quit"
    case menuShow = "menu.show"
    case navLogs = "nav.logs"
    case navOverview = "nav.overview"
    case navPackages = "nav.packages"
    case navUpdates = "nav.updates"
    case overviewAiAuthoring = "overview.aiAuthoring"
    case overviewAppPagesOnly = "overview.appPagesOnly"
    case overviewCdpEndpoint = "overview.cdpEndpoint"
    case overviewConnectedDetail = "overview.connectedDetail"
    case overviewConnectingDetail = "overview.connectingDetail"
    case overviewConnection = "overview.connection"
    case overviewControl = "overview.control"
    case overviewCopied = "overview.copied"
    case overviewCopy = "overview.copy"
    case overviewCopyHint = "overview.copyHint"
    case overviewCopySkill = "overview.copySkill"
    case overviewCopySkillDetail = "overview.copySkillDetail"
    case overviewDisabledDetail = "overview.disabledDetail"
    case overviewEnable = "overview.enable"
    case overviewEnableDetail = "overview.enableDetail"
    case overviewErrorDetail = "overview.errorDetail"
    case overviewInjectionScope = "overview.injectionScope"
    case overviewLoadOrder = "overview.loadOrder"
    case overviewLoadOrderDetail = "overview.loadOrderDetail"
    case overviewManagePackages = "overview.managePackages"
    case overviewOpenCodex = "overview.openCodex"
    case overviewOpenCodexDetail = "overview.openCodexDetail"
    case overviewOpenPackagesDirectory = "overview.openPackagesDirectory"
    case overviewRefreshEveryTwoSeconds = "overview.refreshEveryTwoSeconds"
    case overviewRefreshPolicy = "overview.refreshPolicy"
    case overviewReinject = "overview.reinject"
    case overviewResources = "overview.resources"
    case overviewRestartAndConnect = "overview.restartAndConnect"
    case overviewRestartDetail = "overview.restartDetail"
    case overviewSubtitle = "overview.subtitle"
    case overviewTitle = "overview.title"
    case overviewViewLogs = "overview.viewLogs"
    case packagesActiveVersion = "packages.activeVersion"
    case packagesBuild = "packages.build"
    case packagesBuilding = "packages.building"
    case packagesCannotBuild = "packages.cannotBuild"
    case packagesCheckRemoteUpdates = "packages.checkRemoteUpdates"
    case packagesCheckingRemote = "packages.checkingRemote"
    case packagesChooseDirectory = "packages.chooseDirectory"
    case packagesChooseZip = "packages.chooseZip"
    case packagesClearError = "packages.clearError"
    case packagesClearMessage = "packages.clearMessage"
    case packagesClearSearch = "packages.clearSearch"
    case packagesCollapsed = "packages.collapsed"
    case packagesDependencyConstraint = "packages.dependencyConstraint"
    case packagesDependencyInstalledSource = "packages.dependencyInstalledSource"
    case packagesDependencyNoGitSource = "packages.dependencyNoGitSource"
    case packagesDependencyOrderFirst = "packages.dependencyOrderFirst"
    case packagesDependencyOriginInstallable = "packages.dependencyOrigin.installable"
    case packagesDependencyOriginLocal = "packages.dependencyOrigin.local"
    case packagesDependencyOriginLocalOnly = "packages.dependencyOrigin.localOnly"
    case packagesDependencyOriginManaged = "packages.dependencyOrigin.managed"
    case packagesDependencySelector = "packages.dependencySelector"
    case packagesDependencyStateBlocked = "packages.dependencyState.blocked"
    case packagesDependencyStateCycle = "packages.dependencyState.cycle"
    case packagesDependencyStateDisabled = "packages.dependencyState.disabled"
    case packagesDependencyStateDisabledVersion = "packages.dependencyState.disabledVersion"
    case packagesDependencyStateInvalidRequirement = "packages.dependencyState.invalidRequirement"
    case packagesDependencyStateMissingInstallable = "packages.dependencyState.missingInstallable"
    case packagesDependencyStateMissingLocal = "packages.dependencyState.missingLocal"
    case packagesDependencyStateNotBuilt = "packages.dependencyState.notBuilt"
    case packagesDependencyStateNotBuiltVersion = "packages.dependencyState.notBuiltVersion"
    case packagesDependencyStateSatisfied = "packages.dependencyState.satisfied"
    case packagesDependencyStateSatisfiedVersion = "packages.dependencyState.satisfiedVersion"
    case packagesDependencyStateSelfReference = "packages.dependencyState.selfReference"
    case packagesDependencyStateSourceConflict = "packages.dependencyState.sourceConflict"
    case packagesDependencyStateVersionMismatch = "packages.dependencyState.versionMismatch"
    case packagesDependencySummaryCritical = "packages.dependencySummaryCritical"
    case packagesDependencySummaryOK = "packages.dependencySummaryOK"
    case packagesDependencySummaryPending = "packages.dependencySummaryPending"
    case packagesDetailActiveBuildError = "packages.detail.activeBuildError"
    case packagesDetailCompilerUpdate = "packages.detail.compilerUpdate"
    case packagesDetailDependencyIssues = "packages.detail.dependencyIssues"
    case packagesDetailDependencyUpdate = "packages.detail.dependencyUpdate"
    case packagesDetailLastBuilt = "packages.detail.lastBuilt"
    case packagesDetailPinnedChanged = "packages.detail.pinnedChanged"
    case packagesDetailRemoteAvailable = "packages.detail.remoteAvailable"
    case packagesDetailSourceChanged = "packages.detail.sourceChanged"
    case packagesDetailVersionUpdate = "packages.detail.versionUpdate"
    case packagesDeveloperMode = "packages.developerMode"
    case packagesDeveloperModeDetail = "packages.developerModeDetail"
    case packagesEmptyDetail = "packages.emptyDetail"
    case packagesEmptyTitle = "packages.emptyTitle"
    case packagesEnableDependencies = "packages.enableDependencies"
    case packagesEnablePackage = "packages.enablePackage"
    case packagesEnabledSummary = "packages.enabledSummary"
    case packagesExpanded = "packages.expanded"
    case packagesFilter = "packages.filter"
    case packagesFilterAll = "packages.filter.all"
    case packagesFilterDisabled = "packages.filter.disabled"
    case packagesFilterEnabled = "packages.filter.enabled"
    case packagesFilterError = "packages.filter.error"
    case packagesFilterPending = "packages.filter.pending"
    case packagesGitAvailable = "packages.gitAvailable"
    case packagesGitChecking = "packages.gitChecking"
    case packagesGitMissing = "packages.gitMissing"
    case packagesInstallAndBuild = "packages.installAndBuild"
    case packagesInstallDependencies = "packages.installDependencies"
    case packagesInstallLocal = "packages.installLocal"
    case packagesInstallLocalHelp = "packages.installLocalHelp"
    case packagesInstallRemote = "packages.installRemote"
    case packagesInstalling = "packages.installing"
    case packagesInstallingLocal = "packages.installingLocal"
    case packagesLoadOrder = "packages.loadOrder"
    case packagesLoadOrderDetail = "packages.loadOrderDetail"
    case packagesNoDescription = "packages.noDescription"
    case packagesNoMatchDetail = "packages.noMatchDetail"
    case packagesNoMatchTitle = "packages.noMatchTitle"
    case packagesNodeAvailable = "packages.nodeAvailable"
    case packagesNodeChecking = "packages.nodeChecking"
    case packagesNodeMissing = "packages.nodeMissing"
    case packagesNotBuiltDetail = "packages.notBuiltDetail"
    case packagesOpenDirectory = "packages.openDirectory"
    case packagesPackageCountSuffix = "packages.packageCountSuffix"
    case packagesPriority = "packages.priority"
    case packagesPriorityActual = "packages.priorityActual"
    case packagesPriorityAfter = "packages.priorityAfter"
    case packagesPriorityBefore = "packages.priorityBefore"
    case packagesRebuild = "packages.rebuild"
    case packagesRescan = "packages.rescan"
    case packagesResetPriority = "packages.resetPriority"
    case packagesSearchPlaceholder = "packages.searchPlaceholder"
    case packagesSourceVersion = "packages.sourceVersion"
    case packagesStatusActive = "packages.status.active"
    case packagesStatusBuildFailed = "packages.status.buildFailed"
    case packagesStatusBuilding = "packages.status.building"
    case packagesStatusCompilerChanged = "packages.status.compilerChanged"
    case packagesStatusDependency = "packages.status.dependency"
    case packagesStatusDependencyBlocked = "packages.status.dependencyBlocked"
    case packagesStatusDependencyChanged = "packages.status.dependencyChanged"
    case packagesStatusDisabled = "packages.status.disabled"
    case packagesStatusInstallingRemote = "packages.status.installingRemote"
    case packagesStatusInvalid = "packages.status.invalid"
    case packagesStatusNewVersion = "packages.status.newVersion"
    case packagesStatusNotBuilt = "packages.status.notBuilt"
    case packagesStatusPayloadFailed = "packages.status.payloadFailed"
    case packagesStatusPending = "packages.status.pending"
    case packagesStatusPinnedChanged = "packages.status.pinnedChanged"
    case packagesStatusRemoteFailed = "packages.status.remoteFailed"
    case packagesStatusRemoteUpdate = "packages.status.remoteUpdate"
    case packagesStatusRuntimeFailed = "packages.status.runtimeFailed"
    case packagesStatusSourceChanged = "packages.status.sourceChanged"
    case packagesStatusUnavailable = "packages.status.unavailable"
    case packagesSubtitle = "packages.subtitle"
    case packagesSyncAndBuild = "packages.syncAndBuild"
    case packagesTitle = "packages.title"
    case packagesUpdateAndBuild = "packages.updateAndBuild"
    case packagesUpdateBuild = "packages.updateBuild"
    case packagesUpdateToVersion = "packages.updateToVersion"
    case packagesUserPriority = "packages.userPriority"
    case remoteClose = "remote.close"
    case remoteInstall = "remote.install"
    case remoteRepository = "remote.repository"
    case remoteRepositoryPlaceholder = "remote.repositoryPlaceholder"
    case remoteSelector = "remote.selector"
    case remoteSubtitle = "remote.subtitle"
    case remoteTitle = "remote.title"
    case remoteValidationDetail = "remote.validationDetail"
    case selectorBranch = "selector.branch"
    case selectorBranchDefault = "selector.branchDefault"
    case selectorBranchValue = "selector.branchValue"
    case selectorCommit = "selector.commit"
    case selectorCommitValue = "selector.commitValue"
    case selectorGithubLatestRelease = "selector.githubLatestRelease"
    case selectorGithubRelease = "selector.githubRelease"
    case selectorGithubReleaseValue = "selector.githubReleaseValue"
    case selectorLatestSemverTag = "selector.latestSemverTag"
    case selectorTag = "selector.tag"
    case selectorTagValue = "selector.tagValue"
    case statusCodexNotRunningDetail = "status.codexNotRunning.detail"
    case statusCodexNotRunningTitle = "status.codexNotRunning.title"
    case statusConnectedMany = "status.connected.many"
    case statusConnectedOne = "status.connected.one"
    case statusDisabledTitle = "status.disabled.title"
    case statusErrorTitle = "status.error.title"
    case statusLaunchingCodexTitle = "status.launchingCodex.title"
    case statusRestartRequiredDetail = "status.restartRequired.detail"
    case statusRestartRequiredTitle = "status.restartRequired.title"
    case statusStartingTitle = "status.starting.title"
    case statusWaitingForCDPTitle = "status.waitingForCDP.title"
    case statusWaitingForPageDetail = "status.waitingForPage.detail"
    case statusWaitingForPageTitle = "status.waitingForPage.title"
    case updateApplyProgress = "update.applyProgress"
    case updateAutoCheck = "update.autoCheck"
    case updateAvailable = "update.available"
    case updateChannel = "update.channel"
    case updateChannelBeta = "update.channel.beta"
    case updateChannelBetaDetail = "update.channel.betaDetail"
    case updateChannelStable = "update.channel.stable"
    case updateChannelStableDetail = "update.channel.stableDetail"
    case updateCheck = "update.check"
    case updateCheckFailed = "update.checkFailed"
    case updateCheckFirst = "update.checkFirst"
    case updateChecking = "update.checking"
    case updateCurrent = "update.current"
    case updateCurrentVersion = "update.currentVersion"
    case updateDownload = "update.download"
    case updateInstall = "update.install"
    case updateInstallFailed = "update.installFailed"
    case updateLastCheck = "update.lastCheck"
    case updateLater = "update.later"
    case updateLatestVersion = "update.latestVersion"
    case updateNever = "update.never"
    case updateNoRelease = "update.noRelease"
    case updateNoneAvailable = "update.noneAvailable"
    case updateNotInstalled = "update.notInstalled"
    case updatePromptMessage = "update.promptMessage"
    case updateRepository = "update.repository"
    case updateRestoreReminder = "update.restoreReminder"
    case updateSkip = "update.skip"
    case updateSkipMessage = "update.skipMessage"
    case updateSkipped = "update.skipped"
    case updateSoftwareUpdate = "update.softwareUpdate"
    case updateSubtitle = "update.subtitle"
    case updateTitle = "update.title"
    case updateVersionBuild = "update.versionBuild"
    case updateViewRelease = "update.viewRelease"
}

struct BackendPresentationTokens: Codable, Equatable, Sendable {
    let windowMinWidth: Int
    let windowMinHeight: Int
    let navigationWidth: Int
    let contentMaxWidth: Int
    let pagePadding: Int
    let sectionSpacing: Int
    let cardPadding: Int
    let cardCornerRadius: Int
    let controlSpacing: Int
    let compactSpacing: Int
    let statusIconSize: Int
    let animationFastMS: Int
    let animationStandardMS: Int
    let accentColor: String
    let successColor: String
    let warningColor: String
    let dangerColor: String
}

struct BackendAvailableActions: Codable, Equatable, Sendable {
    let openCodex: Bool
    let restartCodex: Bool
    let reinject: Bool
    let openPackagesDirectory: Bool
    let openLogFile: Bool
    let openRepository: Bool
    let setEnabled: Bool
    let setDeveloperMode: Bool
    let reloadPackages: Bool
    let installLocalPackage: Bool
    let installRemotePackage: Bool
    let checkNodeEnvironment: Bool
    let checkGitEnvironment: Bool
    let checkManagedPackageUpdates: Bool
    let refreshLog: Bool
    let clearLog: Bool
    let readAuthoringPrompt: Bool
    let checkAppUpdate: Bool
    let setUpdatePreferences: Bool
    let installAppUpdate: Bool
}

struct BackendStatusPresentation: Codable, Equatable, Sendable {
    let title: String
    let detail: String
    let tone: String
}

struct BackendPlatformPresentation: Codable, Equatable, Sendable {
    let operatingSystem: String
    let architecture: String
    let cdpEndpoint: String
    let repositoryURL: String
    let updateInstallStrategy: String
}

struct BackendPresentationContract: Codable, Equatable, Sendable {
    let version: Int
    let locale: String
    let text: [String: String]
    let tokens: BackendPresentationTokens
    let actions: BackendAvailableActions
    let status: BackendStatusPresentation
    let platform: BackendPlatformPresentation
}

enum GeneratedPresentationDefaults {
    static let text: [PresentationTextKey: String] = [
        .appBackendDateMalformed: "无法解析 Go 后端返回的日期：{value}",
        .appBackendMalformed: "Go 后端返回了无法解析的响应。",
        .appBackendMissing: "应用目录中缺少 Go 后端可执行文件。",
        .appBackendNotRunning: "Go 后端尚未运行。",
        .appBackendRequestCreateFailed: "无法创建 Go 后端请求。",
        .appBackendRequestFailed: "Go 后端请求失败。",
        .appBackendTerminated: "Go 后端已退出（状态码 {status}）。",
        .appName: "Codex Tweaks",
        .appProtocolMismatch: "Go 后端协议版本不匹配。",
        .commonCancel: "取消",
        .commonClose: "关闭",
        .commonConfirm: "确认",
        .commonCopy: "复制",
        .commonOk: "好",
        .commonOpen: "打开",
        .dialogRestartMessage: "Codex 只有在启动时才能开启 CDP。重启后 Codex Tweaks 会自动恢复注入。",
        .dialogRestartTitle: "重新启动 Codex？",
        .logsClear: "清除日志",
        .logsClearFailed: "无法清除日志",
        .logsClearMessage: "日志文件中的现有记录将被永久删除，此操作无法撤销。",
        .logsClearTitle: "清除所有日志？",
        .logsEmpty: "暂无日志",
        .logsOpenFile: "打开日志文件",
        .logsRefresh: "刷新",
        .logsSubtitle: "查看启动、连接和注入过程。",
        .logsTitle: "连接与注入日志",
        .menuQuit: "退出 Codex Tweaks",
        .menuShow: "显示 Codex Tweaks",
        .navLogs: "运行日志",
        .navOverview: "概览",
        .navPackages: "功能包",
        .navUpdates: "关于与更新",
        .overviewAiAuthoring: "交给 AI 编写",
        .overviewAppPagesOnly: "仅 app:// 页面",
        .overviewCdpEndpoint: "CDP 端点",
        .overviewConnectedDetail: "已编译且启用的功能包已应用到 Codex。",
        .overviewConnectingDetail: "Codex Tweaks 正在建立本地连接。",
        .overviewConnection: "连接方式",
        .overviewControl: "控制",
        .overviewCopied: "已复制",
        .overviewCopy: "复制 Skill",
        .overviewCopyHint: "复制后可粘贴给 Codex 或其他智能体",
        .overviewCopySkill: "复制 Codex Tweaks 功能包开发 Skill",
        .overviewCopySkillDetail: "复制内容直接来自项目内统一的 SKILL.md，与功能包协议、依赖和验证约束始终使用同一份来源。粘贴后再追加具体需求。",
        .overviewDisabledDetail: "Codex 保持运行，但不会应用任何自定义内容。",
        .overviewEnable: "启用界面增强",
        .overviewEnableDetail: "停用后会清理已注入的样式、组件和事件监听器。",
        .overviewErrorDetail: "请查看运行日志了解详细原因。",
        .overviewInjectionScope: "注入范围",
        .overviewLoadOrder: "包加载顺序",
        .overviewLoadOrderDetail: "依赖拓扑优先，再按用户有效优先级从小到大",
        .overviewManagePackages: "管理功能包",
        .overviewOpenCodex: "打开 Codex",
        .overviewOpenCodexDetail: "打开 Codex 后会自动建立连接。",
        .overviewOpenPackagesDirectory: "在文件管理器中管理功能包",
        .overviewRefreshEveryTwoSeconds: "每 2 秒检查功能包与窗口",
        .overviewRefreshPolicy: "刷新策略",
        .overviewReinject: "重新注入",
        .overviewResources: "资源目录",
        .overviewRestartAndConnect: "重启并连接",
        .overviewRestartDetail: "需要重新启动 Codex 才能开启本地调试端口。",
        .overviewSubtitle: "连接状态、注入控制与常用入口集中在一个窗口中。",
        .overviewTitle: "管理 Codex 的本地界面增强",
        .overviewViewLogs: "查看日志",
        .packagesActiveVersion: "已激活 v{version}",
        .packagesBuild: "编译",
        .packagesBuilding: "编译中…",
        .packagesCannotBuild: "无法编译",
        .packagesCheckRemoteUpdates: "检查远程更新",
        .packagesCheckingRemote: "正在检查…",
        .packagesChooseDirectory: "选择功能包目录",
        .packagesChooseZip: "选择 ZIP 文件",
        .packagesClearError: "清除安装错误",
        .packagesClearMessage: "清除安装提示",
        .packagesClearSearch: "清除搜索与筛选",
        .packagesCollapsed: "已折叠",
        .packagesDependencyConstraint: "依赖约束",
        .packagesDependencyInstalledSource: "本机已安装来源：{url}",
        .packagesDependencyNoGitSource: "未声明 Git 来源，仅在本地查找",
        .packagesDependencyOrderFirst: "依赖顺序优先",
        .packagesDependencyOriginInstallable: "Git 可安装",
        .packagesDependencyOriginLocal: "本地提供",
        .packagesDependencyOriginLocalOnly: "仅本地",
        .packagesDependencyOriginManaged: "Git 管理",
        .packagesDependencySelector: "{type}：{value}",
        .packagesDependencyStateBlocked: "依赖链阻塞",
        .packagesDependencyStateCycle: "循环依赖",
        .packagesDependencyStateDisabled: "已停用",
        .packagesDependencyStateDisabledVersion: "已停用 · v{version}",
        .packagesDependencyStateInvalidRequirement: "版本范围无效",
        .packagesDependencyStateMissingInstallable: "可从 Git 安装",
        .packagesDependencyStateMissingLocal: "本地缺失",
        .packagesDependencyStateNotBuilt: "尚未编译",
        .packagesDependencyStateNotBuiltVersion: "尚未编译 · v{version}",
        .packagesDependencyStateSatisfied: "正常",
        .packagesDependencyStateSatisfiedVersion: "正常 · v{version}",
        .packagesDependencyStateSelfReference: "依赖自身",
        .packagesDependencyStateSourceConflict: "来源冲突",
        .packagesDependencyStateVersionMismatch: "v{version} 不匹配",
        .packagesDependencySummaryCritical: "依赖 {total} · {pending} 个异常",
        .packagesDependencySummaryOK: "依赖 {total}/{total} 正常",
        .packagesDependencySummaryPending: "依赖 {total} · {pending} 个需处理",
        .packagesDetailActiveBuildError: "当前仍运行 v{version}。{message}",
        .packagesDetailCompilerUpdate: "当前产物由 esbuild {version} 生成。",
        .packagesDetailDependencyIssues: "有 {count} 个依赖问题，展开依赖详情可查看具体状态。",
        .packagesDetailDependencyUpdate: "当前编译产物仍在运行；需手动同步依赖或构建配置。",
        .packagesDetailLastBuilt: "上次编译：{date}",
        .packagesDetailPinnedChanged: "远端固定 Tag/Release 指向了新的 commit；为避免静默替换，已阻止普通更新。",
        .packagesDetailRemoteAvailable: "{reference} 已更新到 {commit}，点击后下载并编译。",
        .packagesDetailSourceChanged: "当前编译产物仍在运行，新源码尚未激活。",
        .packagesDetailVersionUpdate: "当前仍运行 v{current}，点击后更新到 v{next}。",
        .packagesDeveloperMode: "开发者模式",
        .packagesDeveloperModeDetail: "开发者模式会自动编译已启用包的源码变化；依赖或版本更新仍需手动确认。",
        .packagesEmptyDetail: "在 packages 目录中创建包目录和 package.json 后重新扫描。",
        .packagesEmptyTitle: "没有找到功能包",
        .packagesEnableDependencies: "启用依赖",
        .packagesEnablePackage: "启用 {name}",
        .packagesEnabledSummary: "已启用 {enabled} / {total}，已激活 {active}",
        .packagesExpanded: "已展开",
        .packagesFilter: "筛选功能包",
        .packagesFilterAll: "全部",
        .packagesFilterDisabled: "已停用",
        .packagesFilterEnabled: "已启用",
        .packagesFilterError: "异常",
        .packagesFilterPending: "待处理",
        .packagesGitAvailable: "{version} 可用",
        .packagesGitChecking: "正在检测 Git…",
        .packagesGitMissing: "未找到 Git；本地功能包仍可使用，但不能安装或检查远程包。",
        .packagesInstallAndBuild: "安装并编译",
        .packagesInstallDependencies: "安装缺失依赖",
        .packagesInstallLocal: "安装本地包",
        .packagesInstallLocalHelp: "选择功能包目录或 ZIP；校验通过后复制到本地 packages 目录",
        .packagesInstallRemote: "从 Git 安装",
        .packagesInstalling: "正在安装…",
        .packagesInstallingLocal: "正在安全检查并安装本地功能包…",
        .packagesLoadOrder: "加载顺序",
        .packagesLoadOrderDetail: "依赖拓扑优先，其余按有效优先级",
        .packagesNoDescription: "没有提供包说明。",
        .packagesNoMatchDetail: "尝试更换关键词或筛选条件。",
        .packagesNoMatchTitle: "没有匹配的功能包",
        .packagesNodeAvailable: "Node.js {version} 可用",
        .packagesNodeChecking: "正在检测 Node.js…",
        .packagesNodeMissing: "未找到 Node.js、npm 和 npx；安装 Node.js 后重新扫描。",
        .packagesNotBuiltDetail: "点击编译后才会加载到页面。",
        .packagesOpenDirectory: "在文件管理器中打开功能包",
        .packagesPackageCountSuffix: " 等 {count} 个包",
        .packagesPriority: "优先级",
        .packagesPriorityActual: "实际加载顺序 #{position}。用户优先级 {priority} 仍用于和没有依赖路径的功能包排序。",
        .packagesPriorityAfter: "{name} 依赖于 {dependencies}，因此必须在这些包之后加载。",
        .packagesPriorityBefore: "{dependencies} 依赖于 {name}，因此当前包必须先于这些包加载。",
        .packagesRebuild: "重新编译",
        .packagesRescan: "重新扫描",
        .packagesResetPriority: "恢复包默认优先级 {priority}",
        .packagesSearchPlaceholder: "搜索功能包",
        .packagesSourceVersion: "源 v{version}",
        .packagesStatusActive: "已激活",
        .packagesStatusBuildFailed: "编译失败",
        .packagesStatusBuilding: "正在编译",
        .packagesStatusCompilerChanged: "编译器有更新",
        .packagesStatusDependency: "依赖待处理",
        .packagesStatusDependencyBlocked: "依赖阻塞",
        .packagesStatusDependencyChanged: "依赖或配置更新",
        .packagesStatusDisabled: "已停用",
        .packagesStatusInstallingRemote: "正在处理远程包",
        .packagesStatusInvalid: "配置无效",
        .packagesStatusNewVersion: "发现新版本",
        .packagesStatusNotBuilt: "尚未编译",
        .packagesStatusPayloadFailed: "产物读取失败",
        .packagesStatusPending: "待编译",
        .packagesStatusPinnedChanged: "固定引用已变化",
        .packagesStatusRemoteFailed: "远程操作失败",
        .packagesStatusRemoteUpdate: "远程有更新",
        .packagesStatusRuntimeFailed: "运行失败",
        .packagesStatusSourceChanged: "源码有更新",
        .packagesStatusUnavailable: "不可用",
        .packagesSubtitle: "每个目录是一个独立包。源码更新不会直接生效，手动编译成功后才会原子切换。",
        .packagesSyncAndBuild: "同步并编译",
        .packagesTitle: "按包管理页面增强",
        .packagesUpdateAndBuild: "更新并编译",
        .packagesUpdateBuild: "更新编译",
        .packagesUpdateToVersion: "更新到 v{version}",
        .packagesUserPriority: "{name} 用户优先级",
        .remoteClose: "关闭",
        .remoteInstall: "安装",
        .remoteRepository: "仓库地址",
        .remoteRepositoryPlaceholder: "https://github.com/owner/package.git",
        .remoteSelector: "版本选择",
        .remoteSubtitle: "程序会解析远程引用、锁定精确 commit，并在临时目录校验包格式后保存不可变源码。",
        .remoteTitle: "从 Git 安装功能包",
        .remoteValidationDetail: "安装会校验 package.json、API 版本、SemVer、入口、包依赖与 npm 锁文件。通过后新包默认保持停用；有 Node.js 时会继续下载锁定依赖并编译，但不会自动启用。",
        .selectorBranch: "指定分支",
        .selectorBranchDefault: "main",
        .selectorBranchValue: "分支名称",
        .selectorCommit: "指定 Commit",
        .selectorCommitValue: "Commit SHA",
        .selectorGithubLatestRelease: "GitHub 最新 Release",
        .selectorGithubRelease: "指定 GitHub Release",
        .selectorGithubReleaseValue: "Release 的 Tag",
        .selectorLatestSemverTag: "最新 SemVer Tag",
        .selectorTag: "指定 Tag",
        .selectorTagValue: "Tag 名称",
        .statusCodexNotRunningDetail: "可以重新打开 Codex",
        .statusCodexNotRunningTitle: "Codex 未运行",
        .statusConnectedMany: "已连接 {count} 个窗口",
        .statusConnectedOne: "已连接 Codex",
        .statusDisabledTitle: "界面增强已停用",
        .statusErrorTitle: "连接异常",
        .statusLaunchingCodexTitle: "正在启动 Codex",
        .statusRestartRequiredDetail: "当前 Codex 未开启本地 CDP 端口",
        .statusRestartRequiredTitle: "Codex 需要重启",
        .statusStartingTitle: "正在启动",
        .statusWaitingForCDPTitle: "正在等待调试端口",
        .statusWaitingForPageDetail: "调试端口可用，尚未发现 app:// 页面",
        .statusWaitingForPageTitle: "正在等待 Codex 页面",
        .updateApplyProgress: "正在下载并安装完整更新…",
        .updateAutoCheck: "启动 Codex Tweaks 时自动检查更新",
        .updateAvailable: "有新版本",
        .updateChannel: "更新通道",
        .updateChannelBeta: "测试版",
        .updateChannelBetaDetail: "检查正式版、Beta 与 RC",
        .updateChannelStable: "正式版",
        .updateChannelStableDetail: "仅检查正式发布版本",
        .updateCheck: "检查更新",
        .updateCheckFailed: "检查更新失败：{message}",
        .updateCheckFirst: "请先检查更新。",
        .updateChecking: "正在检查…",
        .updateCurrent: "已是最新",
        .updateCurrentVersion: "当前版本",
        .updateDownload: "下载 {version}",
        .updateInstall: "安装 {version}",
        .updateInstallFailed: "安装更新失败：{message}",
        .updateLastCheck: "上次检查",
        .updateLater: "稍后",
        .updateLatestVersion: "通道最新版本",
        .updateNever: "从未",
        .updateNoRelease: "当前通道还没有可用的 GitHub Release。",
        .updateNoneAvailable: "当前没有可安装的更新。",
        .updateNotInstalled: "当前是便携构建；请先使用 Setup.exe 安装后再使用自动更新。",
        .updatePromptMessage: "当前版本为 {current}，新版本 {latest} 已可下载。",
        .updateRepository: "项目主页",
        .updateRestoreReminder: "恢复提醒",
        .updateSkip: "跳过此版本",
        .updateSkipMessage: "已跳过版本 {version}，仍可手动下载或恢复提醒。",
        .updateSkipped: "已跳过",
        .updateSoftwareUpdate: "软件更新",
        .updateSubtitle: "选择更新通道，并从 GitHub Releases 获取适合当前设备的版本。",
        .updateTitle: "关于与更新",
        .updateVersionBuild: "版本 {version}（构建 {build}）",
        .updateViewRelease: "查看 Release",
    ]
    static let contract = BackendPresentationContract(version: 1, locale: "zh-CN", text: Dictionary(uniqueKeysWithValues: text.map { ($0.key.rawValue, $0.value) }), tokens: BackendPresentationTokens(windowMinWidth: 980, windowMinHeight: 680, navigationWidth: 220, contentMaxWidth: 1120, pagePadding: 32, sectionSpacing: 28, cardPadding: 20, cardCornerRadius: 14, controlSpacing: 12, compactSpacing: 7, statusIconSize: 36, animationFastMS: 120, animationStandardMS: 220, accentColor: "#0A84FF", successColor: "#30D158", warningColor: "#FF9F0A", dangerColor: "#FF453A"), actions: BackendAvailableActions(openCodex: true, restartCodex: false, reinject: false, openPackagesDirectory: true, openLogFile: true, openRepository: true, setEnabled: true, setDeveloperMode: true, reloadPackages: true, installLocalPackage: true, installRemotePackage: false, checkNodeEnvironment: true, checkGitEnvironment: true, checkManagedPackageUpdates: false, refreshLog: true, clearLog: false, readAuthoringPrompt: false, checkAppUpdate: true, setUpdatePreferences: true, installAppUpdate: false), status: BackendStatusPresentation(title: "正在启动", detail: "Codex Tweaks 正在建立本地连接。", tone: "accent"), platform: BackendPlatformPresentation(operatingSystem: "darwin", architecture: "universal", cdpEndpoint: "127.0.0.1:9335", repositoryURL: "https://github.com/cr-zhichen/codex-tweaks", updateInstallStrategy: "openDownload"))
}
