package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"unicode"

	"github.com/cr-zhichen/codex-tweaks/backend/internal/core"
)

type outputFile struct {
	path string
	data []byte
}

func main() {
	root := flag.String("root", "..", "repository root")
	check := flag.Bool("check", false, "verify generated files without writing")
	flag.Parse()

	files, err := generatedFiles(*root)
	if err != nil {
		fatal(err)
	}
	for _, file := range files {
		if *check {
			current, readErr := os.ReadFile(file.path)
			if readErr != nil || !bytes.Equal(current, file.data) {
				fatal(fmt.Errorf("generated contract is stale: %s", file.path))
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(file.path), 0o755); err != nil {
			fatal(err)
		}
		if err := os.WriteFile(file.path, file.data, 0o644); err != nil {
			fatal(err)
		}
	}
}

func generatedFiles(root string) ([]outputFile, error) {
	contract := core.NewPresentationContract(core.PresentationState{})
	swiftContract := contract
	swiftContract.Platform = core.PlatformPresentation{
		OperatingSystem:       "darwin",
		Architecture:          "universal",
		CDPEndpoint:           core.CodexCDPEndpoint,
		RepositoryURL:         core.UpdateRepositoryURL,
		UpdateInstallStrategy: "openDownload",
	}
	keys := make([]string, 0, len(contract.Text))
	for key := range contract.Text {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	manifest := struct {
		Version      int                     `json:"version"`
		Locale       string                  `json:"locale"`
		Text         map[string]string       `json:"text"`
		Tokens       core.PresentationTokens `json:"tokens"`
		ActionKeys   []string                `json:"actionKeys"`
		PlatformKeys []string                `json:"platformKeys"`
		StatusTones  []string                `json:"statusTones"`
	}{
		contract.Version,
		contract.Locale,
		contract.Text,
		contract.Tokens,
		jsonFieldNames(reflect.TypeOf(contract.Actions)),
		jsonFieldNames(reflect.TypeOf(contract.Platform)),
		[]string{"accent", "success", "warning", "danger", "neutral"},
	}
	manifestData, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return nil, err
	}
	manifestData = append(manifestData, '\n')

	return []outputFile{
		{filepath.Join(root, "contract", "presentation-contract.json"), manifestData},
		{filepath.Join(root, "app", "Sources", "GeneratedPresentationContract.swift"), generateSwift(keys, swiftContract)},
		{filepath.Join(root, "windows", "CodexTweaks.Windows", "Generated", "PresentationContract.g.cs"), generateCSharp(keys, contract)},
	}, nil
}

func jsonFieldNames(value reflect.Type) []string {
	result := make([]string, 0, value.NumField())
	for index := 0; index < value.NumField(); index++ {
		result = append(result, jsonName(value.Field(index)))
	}
	sort.Strings(result)
	return result
}

func generateSwift(keys []string, contract core.PresentationContract) []byte {
	var result strings.Builder
	result.WriteString("// Generated by backend/cmd/contractgen. Do not edit.\n")
	result.WriteString("import Foundation\n\n")
	result.WriteString("enum PresentationTextKey: String, CaseIterable, Sendable {\n")
	for _, key := range keys {
		fmt.Fprintf(&result, "    case %s = %q\n", swiftIdentifier(key), key)
	}
	result.WriteString("}\n\n")
	for _, value := range []any{
		core.PresentationTokens{}, core.AvailableActions{}, core.StatusPresentation{}, core.PlatformPresentation{}, core.PresentationContract{},
	} {
		writeSwiftStruct(&result, reflect.TypeOf(value))
	}
	result.WriteString("enum GeneratedPresentationDefaults {\n")
	result.WriteString("    static let text: [PresentationTextKey: String] = [\n")
	for _, key := range keys {
		fmt.Fprintf(&result, "        .%s: %s,\n", swiftIdentifier(key), quotedString(contract.Text[key]))
	}
	result.WriteString("    ]\n")
	fmt.Fprintf(
		&result,
		"    static let contract = BackendPresentationContract(version: %d, locale: %s, text: Dictionary(uniqueKeysWithValues: text.map { ($0.key.rawValue, $0.value) }), tokens: %s, actions: %s, status: %s, platform: %s)\n",
		contract.Version,
		quotedString(contract.Locale),
		swiftStructLiteral(reflect.ValueOf(contract.Tokens)),
		swiftStructLiteral(reflect.ValueOf(contract.Actions)),
		swiftStructLiteral(reflect.ValueOf(contract.Status)),
		swiftStructLiteral(reflect.ValueOf(contract.Platform)),
	)
	result.WriteString("}\n")
	return []byte(result.String())
}

func writeSwiftStruct(result *strings.Builder, value reflect.Type) {
	fmt.Fprintf(result, "struct Backend%s: Codable, Equatable, Sendable {\n", value.Name())
	for index := 0; index < value.NumField(); index++ {
		field := value.Field(index)
		name := jsonName(field)
		fmt.Fprintf(result, "    let %s: %s\n", name, swiftType(field.Type))
	}
	result.WriteString("}\n\n")
}

func swiftType(value reflect.Type) string {
	switch value.Kind() {
	case reflect.Bool:
		return "Bool"
	case reflect.Int:
		return "Int"
	case reflect.String:
		return "String"
	case reflect.Map:
		return "[" + swiftType(value.Key()) + ": " + swiftType(value.Elem()) + "]"
	case reflect.Struct:
		return "Backend" + value.Name()
	default:
		panic("unsupported Swift contract type: " + value.String())
	}
}

func swiftStructLiteral(value reflect.Value) string {
	typeOfValue := value.Type()
	var result strings.Builder
	fmt.Fprintf(&result, "Backend%s(", typeOfValue.Name())
	for index := 0; index < typeOfValue.NumField(); index++ {
		if index > 0 {
			result.WriteString(", ")
		}
		field := typeOfValue.Field(index)
		fmt.Fprintf(&result, "%s: %s", jsonName(field), swiftScalarLiteral(value.Field(index)))
	}
	result.WriteString(")")
	return result.String()
}

func swiftScalarLiteral(value reflect.Value) string {
	switch value.Kind() {
	case reflect.Bool:
		if value.Bool() {
			return "true"
		}
		return "false"
	case reflect.Int:
		return fmt.Sprintf("%d", value.Int())
	case reflect.String:
		return quotedString(value.String())
	default:
		panic("unsupported Swift literal type: " + value.Type().String())
	}
}

func generateCSharp(keys []string, contract core.PresentationContract) []byte {
	var result strings.Builder
	result.WriteString("// Generated by backend/cmd/contractgen. Do not edit.\n")
	result.WriteString("using System.Collections.Generic;\n")
	result.WriteString("using System.Text.Json.Serialization;\n\n")
	result.WriteString("namespace CodexTweaks.Windows.Generated;\n\n")
	result.WriteString("internal static class PresentationTextKey\n{\n")
	for _, key := range keys {
		fmt.Fprintf(&result, "    internal const string %s = %q;\n", csharpIdentifier(key), key)
	}
	result.WriteString("}\n\n")
	for _, value := range []any{
		core.PresentationTokens{}, core.AvailableActions{}, core.StatusPresentation{}, core.PlatformPresentation{}, core.PresentationContract{},
	} {
		writeCSharpClass(&result, reflect.TypeOf(value))
	}
	result.WriteString("internal static class PresentationDefaults\n{\n")
	result.WriteString("    internal static IReadOnlyDictionary<string, string> Text { get; } = new Dictionary<string, string>\n    {\n")
	for _, key := range keys {
		fmt.Fprintf(&result, "        [PresentationTextKey.%s] = %s,\n", csharpIdentifier(key), quotedString(contract.Text[key]))
	}
	result.WriteString("    };\n\n")
	result.WriteString("    internal static PresentationTokens Tokens { get; } = new()\n    {\n")
	tokens := reflect.ValueOf(contract.Tokens)
	for index := 0; index < tokens.NumField(); index++ {
		field := tokens.Type().Field(index)
		fmt.Fprintf(&result, "        %s = %s,\n", pascal(jsonName(field)), csharpScalarLiteral(tokens.Field(index)))
	}
	result.WriteString("    };\n}\n")
	return []byte(result.String())
}

func writeCSharpClass(result *strings.Builder, value reflect.Type) {
	fmt.Fprintf(result, "internal sealed class %s\n{\n", value.Name())
	for index := 0; index < value.NumField(); index++ {
		field := value.Field(index)
		name := jsonName(field)
		fmt.Fprintf(result, "    [JsonPropertyName(%q)]\n", name)
		fmt.Fprintf(result, "    public %s %s { get; init; }%s\n\n", csharpType(field.Type), pascal(name), csharpInitializer(field.Type))
	}
	result.WriteString("}\n\n")
}

func csharpType(value reflect.Type) string {
	switch value.Kind() {
	case reflect.Bool:
		return "bool"
	case reflect.Int:
		return "int"
	case reflect.String:
		return "string"
	case reflect.Map:
		return "Dictionary<" + csharpType(value.Key()) + ", " + csharpType(value.Elem()) + ">"
	case reflect.Struct:
		return value.Name()
	default:
		panic("unsupported C# contract type: " + value.String())
	}
}

func csharpInitializer(value reflect.Type) string {
	switch value.Kind() {
	case reflect.String:
		return " = string.Empty;"
	case reflect.Map, reflect.Struct:
		return " = new();"
	default:
		return ""
	}
}

func csharpScalarLiteral(value reflect.Value) string {
	switch value.Kind() {
	case reflect.Bool:
		if value.Bool() {
			return "true"
		}
		return "false"
	case reflect.Int:
		return fmt.Sprintf("%d", value.Int())
	case reflect.String:
		return quotedString(value.String())
	default:
		panic("unsupported C# literal type: " + value.Type().String())
	}
}

func jsonName(field reflect.StructField) string {
	name := strings.Split(field.Tag.Get("json"), ",")[0]
	if name == "" {
		return field.Name
	}
	return name
}

func swiftIdentifier(key string) string  { return camelIdentifier(key, false) }
func csharpIdentifier(key string) string { return camelIdentifier(key, true) }

func camelIdentifier(value string, upperFirst bool) string {
	parts := strings.FieldsFunc(value, func(character rune) bool {
		return !unicode.IsLetter(character) && !unicode.IsDigit(character)
	})
	if len(parts) == 0 {
		return "value"
	}
	var result strings.Builder
	for index, part := range parts {
		if index == 0 && !upperFirst {
			result.WriteString(strings.ToLower(part[:1]) + part[1:])
		} else {
			result.WriteString(strings.ToUpper(part[:1]) + part[1:])
		}
	}
	return result.String()
}

func pascal(value string) string {
	if value == "" {
		return value
	}
	return strings.ToUpper(value[:1]) + value[1:]
}

func quotedString(value string) string {
	data, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return string(data)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
